
# This file is used to configure the Supabase project

project_id = "smjcfloxvfeipewrbrrm"

[auth]
site_url = "https://smjcfloxvfeipewrbrrm.lovable.dev"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[functions]
[functions.create-admin]
verify_jwt = true
