// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smjcfloxvfeipewrbrrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtamNmbG94dmZlaXBld3JicnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDAxMTIsImV4cCI6MjA1OTIxNjExMn0.Yz8gdhLWSbrt52spPj4vbKHqDETG33f7h-4ebCQFvQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);